# Numpy

We have seen python basic data structures in our last section. They are great but lack specialized features for data analysis. Like, adding roows, columns, operating on 2d matrices aren't readily available. So, we will use *numpy* for such functions.



In [17]:
import numpy as np

Numpy operates on *nd* arrays. These are similar to lists but contains homogenous elements but easier to store 2-d data.

In [18]:
l1 = [1,2,3,4]
nd1 = np.array(l1)
print(nd1)

l2 = [5,6,7,8]
nd2 = np.array([l1,l2])
print(nd2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


Sum functions on np.array()

In [19]:
print(nd2.shape)

print(nd2.size)

print(nd2.dtype)

(2, 4)
8
int32


### Question 1

Create an identity 2d-array or matrix (with ones across the diagonal).

[ **Hint: ** You can also use **np.identity()** function ]

In [20]:
# nd3 is an identity matrix, which is 2 dimensional, Achieved through passing 2 as the argument to np.identity function

nd3 = np.identity(2)
print (nd3)


[[1. 0.]
 [0. 1.]]


### Question 2

Create a 2d-array or matrix of order 3x3 with values = 9,8,7,6,5,4,3,2,1 arranged in the same order.

Use: **np.matrix()** function



In [21]:
#nd4 created using np.matrix


In [22]:
nd4 = np.matrix('9,8,7;6,5,4;3,2,1')
print (nd4)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


### Question 3

Reverse both the rows and columns of the given matrix.

Hint: You can use the transpose **.T**)

In [23]:
#nd5 is transpose of nd4


In [24]:
nd5 = np.transpose(nd4)
print (nd5)

[[9 6 3]
 [8 5 2]
 [7 4 1]]


### Question 4
Add + 1 to all the elements in the given matrix.

In [25]:
# To the matrix nd4, 1 has been added to all the elements


In [26]:
ndx=nd4+1
print (ndx)

[[10  9  8]
 [ 7  6  5]
 [ 4  3  2]]


Similarly you can do operations like scalar  substraction, division, multiplication (operating on each element in the matrix)

### Question 5

Find the mean of all elements in the given matrix nd6.
nd6 = [[  1   4   9 121 144 169]
 [ 16  25  36 196 225 256]
 [ 49  64  81 289 324 361]]
 
 Use: **.mean()** function


In [27]:
# The matrix nd6 is created using the matrix function and then np.mean is used to find the average of all elements


In [28]:
nd6 = np.matrix('1 4 9 121 144 169;16 25 36 196 225 256; 49 64 81 289 324 361')
x=np.mean(nd6)
print (x)

131.66666666666666


### Question 7

Find the dot product of two given matrices.

[**Hint:** Use **np.dot()**]

In [29]:
# The matrixc nd8 is the dot product of nd5 and nd6, using the np.dot function

In [30]:
nd8 = np.dot(nd5,nd6)
print (nd8)

[[ 252  378  540 3132 3618 4140]
 [ 186  285  414 2526 2925 3354]
 [ 120  192  288 1920 2232 2568]]
